"use client";
import {useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {getEventCategories,saveEventCategory} from "@/lib/api";
import type {EventCategoryItem} from "@/types/admin";
import {AdminDataState} from "@/components/admin/admin-data-state";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from "@/components/ui/dialog";
type Form=Omit<EventCategoryItem,"id">;
const empty:Form={name:"",icon:"",description:"",displayOrder:100,status:"active",archivedAt:null};
export function CategoryManagementScreen(){
 const query=useQuery({queryKey:["event-categories"],queryFn:getEventCategories}),cache=useQueryClient();
 const [search,setSearch]=useState(""),[showArchived,setShowArchived]=useState(false),[open,setOpen]=useState(false),[id,setId]=useState<string|null>(null),[form,setForm]=useState<Form>(empty),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 function edit(row?:EventCategoryItem){setId(row?.id??null);setForm(row??empty);setReason("");setError("");setOpen(true);}
 async function save(){if(busy)return;setBusy(true);setError("");try{await saveEventCategory(id,form,reason);await cache.invalidateQueries({queryKey:["event-categories"]});setOpen(false);}catch(e){setError(e instanceof Error?e.message:"Could not save category");}finally{setBusy(false);}}
 if(query.isPending)return <AdminDataState title="categories" loading/>;
 if(query.isError)return <AdminDataState title="categories" error={query.error} onRetry={()=>void query.refetch()}/>;
 const rows=query.data.filter(c=>(showArchived||!c.archivedAt)&&c.name.toLowerCase().includes(search.toLowerCase()));
 return <div className="space-y-4"><p className="text-sm text-muted-foreground">The app uses enabled categories for hosting, communities, interests and discovery. Disabled or archived categories retain historical links and cannot receive new assignments.</p><div className="flex flex-wrap items-center gap-3"><Input aria-label="Search categories" placeholder="Search categories" value={search} onChange={e=>setSearch(e.target.value)} className="max-w-sm"/><label className="text-sm"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Include archived</label><Button onClick={()=>edit()}>Add category</Button></div>
 <div className="overflow-x-auto rounded border"><table className="w-full text-left text-sm"><thead><tr>{["Category","Description","Order","Status","Actions"].map(v=><th className="p-3" key={v}>{v}</th>)}</tr></thead><tbody>{rows.map(c=><tr className="border-t" key={c.id}><td className="p-3">{c.icon} {c.name}</td><td>{c.description||"—"}</td><td>{c.displayOrder}</td><td>{c.archivedAt?"Archived":c.status}</td><td><Button variant="outline" onClick={()=>edit(c)}>Manage {c.name}</Button></td></tr>)}</tbody></table>{!rows.length&&<p className="p-4">No matching categories.</p>}</div>
 <Dialog open={open} onOpenChange={busy?()=>{}:setOpen}><DialogContent><DialogHeader><DialogTitle>{id?"Edit category":"Create category"}</DialogTitle><DialogDescription>Changes are saved to the shared catalog and recorded in the Admin audit.</DialogDescription></DialogHeader><div className="space-y-3"><label className="block">Name<Input aria-label="Category name" maxLength={80} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="block">Icon (emoji)<Input aria-label="Category icon" maxLength={32} value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})}/></label><label className="block">Description<Input aria-label="Category description" maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="block">Display order<Input aria-label="Category display order" type="number" min={0} max={10000} value={form.displayOrder} onChange={e=>setForm({...form,displayOrder:Number(e.target.value)})}/></label><label className="block">Status<select aria-label="Category status" className="ml-3 rounded border bg-background p-2" value={form.status} onChange={e=>setForm({...form,status:e.target.value as Form["status"]})}><option value="active">Enabled</option><option value="disabled">Disabled</option></select></label>{id&&<label className="block"><input type="checkbox" checked={!!form.archivedAt} onChange={e=>setForm({...form,archivedAt:e.target.checked?new Date().toISOString():null})}/> Archived (uncheck to restore)</label>}<label className="block">Reason<textarea aria-label="Category change reason" className="block w-full rounded border bg-background p-2" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||form.name.trim().length<2||reason.trim().length<5} onClick={save}>{busy?"Saving…":"Save category"}</Button></DialogFooter></DialogContent></Dialog></div>;
}
