"use client";
import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import Link from "next/link";
import {getLeaderboard} from "@/lib/api";
import type {LeaderboardPeriod} from "@/types/admin";
import {Button} from "@/components/ui/button";
import {AdminDataState} from "@/components/admin/admin-data-state";
export function LeaderboardTable(){const [period,setPeriod]=useState<LeaderboardPeriod>("monthly");const query=useQuery({queryKey:["leaderboard",period],queryFn:()=>getLeaderboard(period)});return <div className="space-y-4"><p>Ranked by recorded positive Nitro awards in the selected rolling UTC period, including referrals. Spending does not reduce earned Nitro. Deactivated or restricted members are excluded. Ranks derive from the ledger and cannot be reset independently.</p><div className="flex gap-2">{([["weekly","Last 7 days"],["monthly","Last 30 days"],["all_time","All time"]] as const).map(([value,label])=><Button key={value} variant={period===value?"default":"outline"} onClick={()=>setPeriod(value)}>{label}</Button>)}<Button variant="outline" onClick={()=>void query.refetch()}>Refresh</Button></div>{query.isPending?<AdminDataState title="leaderboard" loading/>:query.error?<AdminDataState title="leaderboard" error={query.error} onRetry={()=>void query.refetch()}/>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Rank","Member","Nitro earned","Hosted","Joined","Referrals"].map(t=><th className="p-3" key={t}>{t}</th>)}</tr></thead><tbody>{query.data.map(r=><tr className="border-t" key={r.userId}><td className="p-3">{r.rank}</td><td><Link href={`/users/${r.userId}`} className="underline">{r.name}</Link></td><td>{r.coinsEarned}</td><td>{r.eventsHosted}</td><td>{r.eventsJoined}</td><td>{r.referrals}</td></tr>)}</tbody></table>{!query.data.length&&<p>No eligible members.</p>}</div>}</div>}
