"use client";
import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {listWorkspace,saveWorkspace,sendWorkspace,scheduleWorkspace,type WorkspaceDocument,type WorkspaceKind,type WorkspacePayload} from "@/lib/admin-workspace";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {AdminDataState} from "@/components/admin/admin-data-state";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
const blank:WorkspacePayload={name:"",title:"",body:"",channel:"in_app",recipients:[],status:"draft",notes:""};
export function WorkspaceDocuments({kind,title,channel="in_app"}:{kind:WorkspaceKind;title:string;channel?:WorkspacePayload["channel"]}){
 const query=useQuery({queryKey:["workspace",kind],queryFn:()=>listWorkspace(kind)});const [search,setSearch]=useState("");const [archived,setArchived]=useState(false);const [editing,setEditing]=useState<WorkspaceDocument|null>(null);const [reason,setReason]=useState("");const [recipients,setRecipients]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [sendTarget,setSendTarget]=useState<WorkspaceDocument|null>(null);const [schedule,setSchedule]=useState("");
 const monetary=kind==="reward"||kind==="coupon";const rows=(query.data??[]).filter(r=>(archived||!r.archived)&&(kind!=="campaign"||r.payload.channel===channel)&&r.payload.name.toLowerCase().includes(search.toLowerCase()));
 const open=(row?:WorkspaceDocument)=>{setError("");setReason("");setEditing(row??{id:crypto.randomUUID(),kind,payload:{...blank,channel},version:0,status:"draft",archived:false,updated_at:"",sent_at:null,delivered:0,opened:0});setRecipients(row?.payload.recipients?.join(", ")??"");};
 const field=(key:keyof WorkspacePayload,value:string)=>setEditing(r=>r?{...r,payload:{...r.payload,[key]:value}}:null);
 const save=async()=>{if(!editing)return;setBusy(true);setError("");try{const ids=recipients.split(/[\s,]+/).filter(Boolean).map(Number);if(kind==="campaign"&&ids.some(n=>!Number.isSafeInteger(n)||n<=0))throw Error("Use positive integer recipient IDs separated by commas.");await saveWorkspace({...editing,payload:{...editing.payload,recipients:[...new Set(ids)]}},reason);await query.refetch();setEditing(null);setNotice("Saved to the database.");}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
 const send=async(cancel=false)=>{if(!sendTarget)return;setBusy(true);setError("");try{if(cancel)await scheduleWorkspace(sendTarget,null,reason);else if(schedule)await scheduleWorkspace(sendTarget,new Date(schedule).toISOString(),reason);else await sendWorkspace(sendTarget,reason);await query.refetch();setSendTarget(null);setNotice(cancel?"Schedule cancelled; draft preserved.":schedule?"Schedule saved. Delivery runs within a minute of the chosen time; failures appear on the campaign.":"In-app delivery completed. The campaign cannot be sent twice.");}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
 if(query.isPending)return <AdminDataState title={title} loading/>;if(query.error)return <AdminDataState title={title} error={query.error} onRetry={()=>void query.refetch()}/>;
 return <div className="space-y-4"><p className="text-sm text-muted-foreground">{monetary?"Manage draft proposals. Activation requires the approved redemption provider, eligibility and reward economics. Saving a draft does not create redeemable value or change Nitro balances.":kind==="campaign"?channel==="in_app"?"Send an in-app notification to explicit member IDs. Delivery can be immediate or scheduled, is atomic and recorded once. Review the recipients before sending.":`${channel==="email"?"Email":"Device push"} delivery is not configured. Create, edit and archive persistent drafts; no send is reported without a provider.`:"Reusable message drafts. Saving does not change authentication emails or automatic system messages. Use the draft text when creating a campaign."}</p>
 <div className="flex flex-wrap gap-3"><Input className="max-w-sm" aria-label={`Search ${title}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${title}`}/><Button onClick={()=>open()}>Create draft</Button><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived</label></div>{notice&&<p role="status">{notice}</p>}
 <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{["Name","Status","Updated","Actions"].map(t=><th className="p-3" key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(row=><tr className="border-t" key={row.id}><td className="p-3"><p className="font-medium">{row.payload.name}</p><p className="text-muted-foreground">{row.payload.title}</p>{row.scheduled_at&&<p>Scheduled: {new Date(row.scheduled_at).toLocaleString()}</p>}{row.last_error&&<p role="alert" className="text-destructive">{row.last_error}</p>}{row.status==="sent"&&<p>{row.delivered} delivered · {row.opened} read</p>}</td><td>{row.archived?"Archived":row.scheduled_at?"Scheduled":row.last_error?"Delivery failed":row.status}</td><td>{new Date(row.updated_at).toLocaleString()}</td><td><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>open(row)}>{row.status==="sent"?"Details / archive":"Edit / archive"}</Button>{kind==="campaign"&&!row.archived&&row.status==="draft"&&row.payload.channel==="in_app"&&<Button size="sm" onClick={()=>{setSendTarget(row);setSchedule("");setReason("");setError("")}}>Review delivery</Button>}</div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-4">No matching drafts or campaigns.</p>}</div>
 <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!busy)setEditing(null)}}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing?.version?"Edit":"Create"} {title}</DialogTitle><DialogDescription>Changes are saved only after the server validates the form. Editing content or archiving cancels an existing schedule.</DialogDescription></DialogHeader>{editing&&<div className="space-y-3"><label className="block text-sm">Name<Input value={editing.payload.name} maxLength={160} disabled={editing.status==="sent"} onChange={e=>field("name",e.target.value)}/></label>{!monetary&&<><label className="block text-sm">Title / subject<Input value={editing.payload.title} maxLength={180} disabled={editing.status==="sent"} onChange={e=>field("title",e.target.value)}/></label><label className="block text-sm">Message<textarea className="w-full rounded border p-2" rows={5} value={editing.payload.body} maxLength={1000} disabled={editing.status==="sent"} onChange={e=>field("body",e.target.value)}/></label></>}{monetary&&<label className="block text-sm">Proposal, terms and eligibility<textarea className="w-full rounded border p-2" rows={6} value={editing.payload.notes} maxLength={10000} onChange={e=>field("notes",e.target.value)}/></label>}{kind==="campaign"&&<label className="block text-sm">Recipient member IDs (1–500)<Input value={recipients} disabled={editing.status==="sent"} onChange={e=>setRecipients(e.target.value)} placeholder="70, 71"/></label>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.archived} disabled={!editing.version} onChange={e=>setEditing({...editing,archived:e.target.checked})}/>Archive this document</label><label className="block text-sm">Reason for audit<Input value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1000}/></label>{error&&<p role="alert" className="text-destructive">{error}</p>}<Button disabled={busy||reason.trim().length<5} onClick={()=>void save()}>{busy?"Saving…":"Save"}</Button></div>}</DialogContent></Dialog>
 <Dialog open={!!sendTarget} onOpenChange={v=>{if(!v&&!busy)setSendTarget(null)}}><DialogContent><DialogHeader><DialogTitle>Review in-app delivery</DialogTitle><DialogDescription>This sends the saved message once to the listed members.</DialogDescription></DialogHeader><p className="font-semibold">{sendTarget?.payload.title}</p><p className="whitespace-pre-wrap">{sendTarget?.payload.body}</p><p>Recipients: {sendTarget?.payload.recipients.join(", ")}</p>{sendTarget?.scheduled_at&&<p>Currently scheduled: {new Date(sendTarget.scheduled_at).toLocaleString()}</p>}<label>Schedule (optional, your local time)<Input type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)}/></label><label>Reason<Input value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<Button disabled={busy||reason.trim().length<5} onClick={()=>void send()}>{busy?"Saving…":schedule?"Schedule in-app notification":"Send in-app notification now"}</Button>{sendTarget?.scheduled_at&&<Button variant="outline" disabled={busy||reason.trim().length<5} onClick={()=>void send(true)}>Cancel schedule</Button>}</DialogContent></Dialog>
 </div>
}
